### PR TITLE
Speed up for larger spreadsheets

### PR DESCRIPTION
**Pull request by ajtucker**
We've found that Databaker becomes exponentially slower as spreadsheets increase in size and had a go at some profiling to see what might be going on.

One line that sticks out is in this PR. Looking at the git history, I believe this line was previously removed to help speed things up, but then re-instated with a later commit that was to fix some issue with None values?

There's definitely some logic error in these few lines where `hcells` gets conditionally set and then unconditionally overridden. My understanding is that the condition is based on whether `DIRECT` or `CLOSEST` is used in the definition of the dimension lookup.

Removing the line has made it possible to use Databaker on a spreadsheet with 1400 rows and it appears to still do the same thing as the current Databaker version.

I'll do some more tests to make sure this change doesn't lead to a change in outputs.

### CODE REVIEW

**Comment by StevenMaude** [comment]
@ajtucker Thanks; we're happy to merge and re-release as a new version to PyPI, if users are happy with it at ONS :slightly_smiling_face:

Please bump this thread when you've finished testing, and I'll make sure that's done.

**Comment by StevenMaude** [comment]
:+1:

**Comment by StevenMaude** [comment]
Please let us know when you'd like us to look at this :slightly_smiling_face:

**Comment by mikeAdamss** [comment]
hey @StevenMaude 👋 

We ended up running the pipelines off @ajtucker 's pr branch so all of our recent changes are getting sucked into this pr.

We've got a task to sort out our tagging/branches now that we're actively twiddling databaker, so you can close this and I'll open a fresh one with a bit of contextual information about what's been changed and why in the next week or two when the changes have bedded in (at which point yeah, we'd love for you guys to take a look at it 😄 ).

**Comment by StevenMaude** [comment]
@mikeAdamss ah great! I'll close this one. Hope everything's well with you at ONS besides :slightly_smiling_face:

**Pull request closed without merging**
